---
title: "gini-calculation-in-r"
description: |
  A short description of the post.
author:
  - name: Jonathan Jayes
    url: {}
date: 07-13-2021
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
    highlight: haddock
    highlight_downlit: true
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)

```

## Purpose

Show how to calculate gini coefficient in R

### Creating data

```{r}
tbl <- rnorm(100, 50, sd = 20) %>% as_tibble() %>% 
  mutate(value = abs(value))

tbl %>% 
  arrange(value)

tbl <- tbl %>% rename(var = value)

```

```{r}
gini_jj <- function(tbl, var){
  
  tbl <- tbl %>% arrange(var)
  
  n <- tbl %>% count()
  
  tbl <- tbl %>% mutate(nu = 1/n,
                        nu = cumsum(nu))
  
  tbl <- tbl %>% mutate(c_sum = cumsum(var))
  
  tbl <- tbl %>% mutate(prop = c_sum / max(c_sum))
  
  sum((tbl$prop %>% tail(tbl$n-1))*(tbl$prop %>% head(tbl$n-1)))

  
}
```


```{r}
x <- rnorm(100, 50, sd = 20)
weights = rep(1, 100)


function (x, weights = rep(1, length = length(x))) 
{
    ox <- order(x)
    x <- x[ox]
    weights <- weights[ox]/sum(weights)
    p <- cumsum(weights)
    nu <- cumsum(weights * x)
    n <- length(nu)
    nu <- nu/nu[n]
    sum(nu[-1] * p[-n]) - sum(nu[-n] * p[-1])
}
```



```{r}

tbl <- rep %>% as_tibble() %>% 
  mutate(value = abs(value))

```

